require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/words", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Word. As you add validations to Word, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Word.create! valid_attributes
      get words_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      word = Word.create! valid_attributes
      get word_url(word)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_word_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      word = Word.create! valid_attributes
      get edit_word_url(word)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Word" do
        expect {
          post words_url, params: { word: valid_attributes }
        }.to change(Word, :count).by(1)
      end

      it "redirects to the created word" do
        post words_url, params: { word: valid_attributes }
        expect(response).to redirect_to(word_url(Word.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Word" do
        expect {
          post words_url, params: { word: invalid_attributes }
        }.to change(Word, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post words_url, params: { word: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested word" do
        word = Word.create! valid_attributes
        patch word_url(word), params: { word: new_attributes }
        word.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the word" do
        word = Word.create! valid_attributes
        patch word_url(word), params: { word: new_attributes }
        word.reload
        expect(response).to redirect_to(word_url(word))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        word = Word.create! valid_attributes
        patch word_url(word), params: { word: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested word" do
      word = Word.create! valid_attributes
      expect {
        delete word_url(word)
      }.to change(Word, :count).by(-1)
    end

    it "redirects to the words list" do
      word = Word.create! valid_attributes
      delete word_url(word)
      expect(response).to redirect_to(words_url)
    end
  end
end
